### ISSUE TITLE
Sound doesn't work randomly

### ISSUE THREAD

**Issue by romancin** [geek5nan/Hackintosh-XPS7590#1]
Hi!

Thank you for this! I am trying to change my CLOVER config based on Lulettersoul's repo (working flawlessly) by yours (much more recent and I love OpenCore :) ). Most of it it works correctly, but the main problem I am having is that sound not always work. Have you experienced the same behaviour? Thank you!

**Comment by geek5nan** [comment]
To be honest, I have faced the same problem with you. 

Try to use **boot-arg** `alcid = 30` to instead of `DeviceProperties/Add/PciRoot(0x0)/Pci(0x1f,0x3) -> Layout-id`.

I'm not sure it can be worked, need more test.

**Comment by geek5nan** [comment]
> To be honest, I have faced the same problem with you.
> 
> Try to use **boot-arg** `alcid = 30` to instead of `DeviceProperties/Add/PciRoot(0x0)/Pci(0x1f,0x3) -> Layout-id`.
> 
> I'm not sure it can be worked, need more test.

I change audio injection method with **boot-arg** `alcid=30` last week.
Through a week test, it is a workaround  for me.

**Comment by romancin** [comment]
👍👍 thank you!
