### ISSUE TITLE
Trackpad not working?

### ISSUE THREAD

**Issue by giugrilli** [geek5nan/Hackintosh-XPS7590#4]
I created an install usb, and used your efi folder as it is.

Opencore boots the installer but the touchpad is not working and I cannot use the mouse.
What I am doing wrong?

**Comment by CryptoNeverSleeps** [comment]
I spilled coffee on my XPS in February my replacement XPS 7590 OLED should be delivered next week... going to add Either 2TB or 4TB nVME and 32GB Ram.... check my repos I forked someone’s opencore already for the 7590... For now my Alienware Aurora R7 is my Ultimate Hackintosh.....

Look through my repos there is a 7590 OpenCore build on there.....(Forked)

I have Dell ProCare with accident protection.....

Sent from my iPhone

On Apr 30, 2020, at 4:17 PM, shadowed87 <notifications@github.com> wrote:

﻿

I created an install usb, and used your efi folder as it is.

Opencore boots the installer but the touchpad is not working and I cannot use the mouse.
What I am doing wrong?

**Comment by giugrilli** [comment]
> I spilled coffee on my XPS in February my replacement XPS 7590 OLED should be delivered next week... going to add Either 2TB or 4TB nVME and 32GB Ram.... check my repos I forked someone’s opencore already for the 7590... For now my Alienware Aurora R7 is my Ultimate Hackintosh..... Look through my repos there is a 7590 OpenCore build on there.....(Forked) I have Dell ProCare with accident protection.....

Good thing you have pro Care! :D ... 
I tried your repo but still I have the same results: no trackpad during install and therefore I am stuck... Am I the only one having this issue?

**Comment by geek5nan** [comment]
Is VoodooI2C loaded? Try `sudo kextcache -i /` and restart.

**Comment by giugrilli** [comment]
> Is VoodooI2C loaded? Try `sudo kextcache -i /` and restart.

I do not have an external mouse, so I am unable to use the installer. I will buy a mouse in the following days and report here

**Comment by emmett421** [comment]
I had the same problem as @shadowed87 when I was in the installer and just used a usb mouse. I just assumed it was a fluke. When it was installed and I was in MacOS the trackpad worked fine.

**Comment by CryptoNeverSleeps** [comment]
What repo are you all using?   My OLED XPS 7590 Replacement arrives next week... unless it’s delayed again......

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by giugrilli** [comment]
Ok, i installed everything using an usb mouse, and after the install the trackpad was not working (tried also cryptoneversleeps repo).
Then I run sudo kextcache -i / and restarted. Everything works.
