### ISSUE TITLE
XPS 15 7590 非OLED测试

### ISSUE THREAD

**Issue by gorquan** [geek5nan/Hackintosh-XPS7590#7]
雷电：暂时使用绿联的扩展坞进行测试，绿联扩展坞的网卡正常，尚未对雷电的HDMI进行测试
亮度调节： 可以使用键盘进行亮度调节
睡眠唤醒：可以进行睡眠唤醒，但是唤醒时需要按任意键点亮屏幕，否则持续黑屏

**Comment by geek5nan** [comment]
感谢反馈

**Comment by gorquan** [comment]
我用你的配置升级到0.5.8，加入了CPUFriend，现在变频舒服了好多。感谢你的贡献！
